// Initial data for dashboard modules
import { Module, ModuleId, SequoiaResource } from "./dashboard-types"

// Sequoia resources for each module
export const sequoiaResources: SequoiaResource[] = [
    // Tier 1: Founder (Right to Exist)
    {
        id: 'founder-1',
        title: 'Founder-Market Fit',
        type: 'framework',
        description: 'Why the best founders have deep personal connection to the problem they solve.',
        moduleId: 'founder',
        questionIds: ['why-you'],
    },
    {
        id: 'founder-2',
        title: 'The Idea Maze',
        type: 'article',
        description: 'Understanding the history and evolution of your space gives you an edge.',
        url: 'https://sequoiacap.com',
        moduleId: 'founder',
    },
    {
        id: 'founder-3',
        title: 'Unique Insight',
        type: 'example',
        description: 'Airbnb knew strangers would trust each other. Stripe knew developers wanted simple APIs.',
        moduleId: 'founder',
        questionIds: ['unique-insight'],
    },
    {
        id: 'founder-4',
        title: 'Why Now?',
        type: 'framework',
        description: 'The best companies are built on secular trends and technology shifts.',
        moduleId: 'founder',
        questionIds: ['why-now'],
    },
    // Tier 2: Problem (Urgency)
    {
        id: 'problem-1',
        title: 'Hair on Fire Problem',
        type: 'framework',
        description: 'The best problems are so urgent that customers will use an imperfect solution.',
        moduleId: 'problem',
        questionIds: ['hair-on-fire'],
    },
    {
        id: 'problem-2',
        title: 'Problem Definition Template',
        type: 'guidance',
        description: 'For [target customer], [problem] causes [negative outcome].',
        moduleId: 'problem',
        questionIds: ['workarounds'],
    },
    // Tier 3: Customer (Clarity)
    {
        id: 'customer-1',
        title: 'Early Adopter Profile',
        type: 'framework',
        description: 'Your first 100 customers define your trajectory. Choose wisely.',
        moduleId: 'customer',
        questionIds: ['high-expectation-customer'],
    },
    {
        id: 'customer-2',
        title: 'Customer Evidence Hierarchy',
        type: 'guidance',
        description: 'Revenue > Waitlist > Interviews > Surveys > Assumptions',
        moduleId: 'customer',
        questionIds: ['common-traits'],
    },
    // Tier 4: Product (Differentiation)
    {
        id: 'product-1',
        title: 'Minimum Viable Product',
        type: 'framework',
        description: 'The smallest thing you can build to test your riskiest assumption.',
        moduleId: 'product',
        questionIds: ['wedge'],
    },
    // Tier 5: Market (Viability)
    {
        id: 'market-1',
        title: 'TAM/SAM/SOM Framework',
        type: 'guidance',
        description: 'Bottom-up market sizing is more credible than top-down estimates.',
        moduleId: 'market',
        questionIds: ['path-to-revenue'],
    },
]

export const initialModules: Record<ModuleId, Module> = {
    founder: {
        id: 'founder',
        title: 'Tier 1: Right to Exist',
        description: 'Validate before everything',
        icon: 'User',
        completionPercentage: 0,
        subsections: [
            {
                id: 'tier-1-questions',
                title: 'Foundational Questions',
                description: 'Core validation',
                questions: [
                    {
                        id: 'unique-insight',
                        label: 'What is your unique insight that others don\'t have?',
                        placeholder: 'The secret you know that others don\'t',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'why-you',
                        label: 'Why are YOU the right founder for THIS problem?',
                        placeholder: 'Founder-market fit',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'why-now',
                        label: 'Why NOW—what has changed?',
                        placeholder: 'Technological or market shifts',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'commitment',
                        label: 'Are you willing to commit 10+ years to this?',
                        placeholder: 'Long-term conviction',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                ],
            },
        ],
    },
    problem: {
        id: 'problem',
        title: 'Tier 2: Problem Urgency',
        description: 'Validate before building',
        icon: 'AlertTriangle',
        completionPercentage: 0,
        subsections: [
            {
                id: 'tier-2-questions',
                title: 'Urgency Validation',
                description: 'Is the pain real?',
                questions: [
                    {
                        id: 'hair-on-fire',
                        label: 'Is this a hair-on-fire problem?',
                        placeholder: 'Extreme urgency',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'workarounds',
                        label: 'What workarounds prove the problem is urgent?',
                        placeholder: 'How are they hacking a solution now?',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'imperfect-solution',
                        label: 'Would customers use an imperfect solution?',
                        placeholder: 'Desperation level',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'cost-of-inaction',
                        label: 'Can you quantify the cost of inaction?',
                        placeholder: 'Dollars or time lost',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                ],
            },
        ],
    },
    customer: {
        id: 'customer',
        title: 'Tier 3: Customer Clarity',
        description: 'Validate to scope MVP',
        icon: 'Users',
        completionPercentage: 0,
        subsections: [
            {
                id: 'tier-3-questions',
                title: 'Customer Validation',
                description: 'Who is this for?',
                questions: [
                    {
                        id: 'high-expectation-customer',
                        label: 'Who is your High-Expectation Customer?',
                        placeholder: 'The most demanding user',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'reach-without-intros',
                        label: 'Can you reach them without warm intros?',
                        placeholder: 'Distribution feasibility',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'common-traits',
                        label: 'What do your best potential customers have in common?',
                        placeholder: 'Shared characteristics',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'buyer-vs-user',
                        label: 'Who is the buyer versus the user?',
                        placeholder: 'Decision making unit',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                ],
            },
        ],
    },
    product: {
        id: 'product',
        title: 'Tier 4: Solution Differentiation',
        description: 'Validate through conversations',
        icon: 'Package',
        completionPercentage: 0,
        subsections: [
            {
                id: 'tier-4-questions',
                title: 'Product Validation',
                description: 'Why you win',
                questions: [
                    {
                        id: 'eureka-moment',
                        label: 'What\'s your eureka moment?',
                        placeholder: 'The core breakthrough',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'different-vs-better',
                        label: 'Are you different, or merely better?',
                        placeholder: 'Category creation vs improvement',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'wedge',
                        label: 'What\'s your wedge?',
                        placeholder: 'Complete entry point',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'lightbulb-moment',
                        label: 'What\'s the lightbulb moment in your pitch?',
                        placeholder: 'When do they get it?',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                ],
            },
        ],
    },
    market: {
        id: 'market',
        title: 'Tier 5: Business Viability',
        description: 'Validate before scaling',
        icon: 'TrendingUp',
        completionPercentage: 0,
        subsections: [
            {
                id: 'tier-5-questions',
                title: 'Business Validation',
                description: 'Can this scale?',
                questions: [
                    {
                        id: 'willingness-to-pay',
                        label: 'Will customers pay enough to build a business?',
                        placeholder: 'Unit economics check',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'path-to-revenue',
                        label: 'Can you chart a path to $500M revenue?',
                        placeholder: 'Scale potential',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'defensibility',
                        label: 'What defensibility develops over time?',
                        placeholder: 'Moats (network effects, data, etc.)',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                    {
                        id: 'winning-plan',
                        label: 'What\'s your plan to win against alternatives?',
                        placeholder: 'Competitive strategy',
                        type: 'textarea',
                        value: '',
                        completed: false,
                    },
                ],
            },
        ],
    },
}
