"use client"

import { useAppStore } from "@/lib/store"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { ArrowLeft, Printer } from "lucide-react"
import { useEffect, useState } from "react"
import { ModuleId } from "@/lib/dashboard-types"

export default function InvestorMemoPage() {
  const router = useRouter()
  const { modules, dashboardUnlocked } = useAppStore()
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    if (!dashboardUnlocked) {
      router.push("/")
    }
  }, [dashboardUnlocked, router])

  if (!mounted || !dashboardUnlocked) return null

  // Helper to get value securely
  const getValue = (moduleId: ModuleId, questionId: string) => {
    const module = modules[moduleId]
    if (!module) return null
    
    for (const subsection of module.subsections) {
      const question = subsection.questions.find((q) => q.id === questionId)
      if (question && question.value) {
        if (Array.isArray(question.value)) return question.value.join(", ")
        return question.value
      }
    }
    return null
  }

  const sections = [
    {
      title: "1. The Opportunity (Why Now)",
      content: getValue('founder', 'why-now')
    },
    {
      title: "2. The Problem",
      content: getValue('problem', 'hair-on-fire')
    },
    {
        title: "3. Current Workarounds",
        content: getValue('problem', 'workarounds')
    },
    {
      title: "4. The Solution (Wedge)",
      content: getValue('product', 'wedge')
    },
    {
      title: "5. Target Customer",
      content: getValue('customer', 'high-expectation-customer')
    },
    {
      title: "6. Unique Insight",
      content: getValue('founder', 'unique-insight')
    },
    {
        title: "7. Why You (Founder-Market Fit)",
        content: getValue('founder', 'why-you')
    },
    {
      title: "8. Business Model",
      content: getValue('market', 'path-to-revenue')
    }
  ]

  return (
    <main className="min-h-screen bg-background py-16 px-4 md:px-8">
      <div className="max-w-4xl mx-auto space-y-8">
        
        {/* Header Actions */}
        <div className="flex items-center justify-between print:hidden">
          <Button variant="ghost" className="gap-2" onClick={() => router.push("/dashboard")}>
            <ArrowLeft className="w-4 h-4" />
            Back to Dashboard
          </Button>
          
          <Button variant="outline" className="gap-2" onClick={() => window.print()}>
            <Printer className="w-4 h-4" />
            Print Memo
          </Button>
        </div>

        {/* Memo Document */}
        <div className="bg-white dark:bg-card border border-border rounded-xl p-8 md:p-12 shadow-sm space-y-12">
          
          <div className="border-b border-border pb-8">
             <h1 className="text-3xl md:text-4xl font-serif font-medium text-foreground mb-4">
               Investment Memo
             </h1>
             <p className="text-muted-foreground text-lg">
               Confidential — Generated via Sequoia Launchpad
             </p>
          </div>

          <div className="space-y-10">
            {sections.map((section, idx) => (
              <section key={idx} className="space-y-3">
                <h3 className="text-sm font-bold uppercase tracking-wider text-muted-foreground">
                  {section.title}
                </h3>
                <div className="prose dark:prose-invert max-w-none">
                  {section.content ? (
                    <p className="text-lg leading-relaxed whitespace-pre-wrap">{section.content}</p>
                  ) : (
                    <p className="text-muted-foreground/50 italic">Not yet defined in dashboard.</p>
                  )}
                </div>
              </section>
            ))}
          </div>
          
          <div className="border-t border-border pt-8 text-center">
             <p className="text-sm text-muted-foreground">
               Generated by Sequoia Launchpad Agent
             </p>
          </div>

        </div>
      </div>
    </main>
  )
}
